name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Install Chromedriver
          run: |
            CHROMEDRIVER_VERSION="117.0.2"
            curl -o /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
            unzip /tmp/chromedriver.zip -d /usr/local/bin
            chmod +x /usr/local/bin/chromedriver
        - name: Check Chromedriver Version
          run: chromedriver --version
        - name: Checkout
          uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install
          run: npm install
        - name: Test
          run: npm run wdio
        - uses: actions/upload-artifact@v3
          if: failure()
          with:
            name: allureReport
            path: ./reports/allure/allure-report
